### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/VRTK-Windows-MR-Extension#1]
Might have been better to give this project a more generic name, rather than VRTK specific.

More like "Unity gLTF loader"

**Comment by SimonDarksideJ** [comment]
Any thoughts @tomwim ?

**Comment by tomwim** [comment]
Not sure about this since it actually "just" includes the Controller Visualization. And there is a Unity GLTF loader, right?

**Comment by SimonDarksideJ** [comment]
Only so the visualiser can be used for projects other than VRTK :D

**Comment by tomwim** [comment]
Since the Extension references VRTK classes I am actually against renaming the project for now

**Comment by SimonDarksideJ** [comment]
Ahh, I didn't see that. Darn shame.
