### ISSUE TITLE
Error when used on Standalone Build - MotionControllerVisualizer.cs

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/VRTK-Windows-MR-Extension#2]
When this asset is used on a standalone build, you get a Type error, as the code has not been limited to "UNITY_WSA && UNITY_2017_2_OR_NEWER" like the rest of the code.

"GetPathToButton" on Line 492 uses "InteractionSourceHandedness" which is only available on WSA builds

**Comment by tomwim** [comment]
Fixed
