### ISSUE TITLE
GLTF could not be found

### ISSUE THREAD

**Issue by qubitz** [Innoactive/VRTK-Windows-MR-Extension#3]
Hi there, I think I have a simple issue of my own doing. I'm getting this error after adding this repo to my project:

```
Assets/Extensions/VRTK-Windows-MR-Extension/GLTF/Scripts/GLTFUnityHelpers.cs(113,23): error CS0246: The type or namespace name `GLTF' could not be found. Are you missing an assembly reference?
```

Do I need to include the UnityGLTF repo in my Unity project?

I followed instructions for setting up the project for WMR controller models through the [readme](https://github.com/thestonefox/VRTK/blob/release/3.3.0-alpha/Assets/VRTK/Source/SDK/WindowsMR/README.md) in the WMR SDK in VRTK and the [readme](https://github.com/Innoactive/VRTK-Windows-MR-Extension/README.md) in this repo. I moved the UMP folder next to Assets, but I'm a bit lost as to how to fix the error.

**Comment by amrittb** [comment]
Having the same issue. Any way to fix this?

**Comment by qubitz** [comment]
I haven't found any real solution, but instead have been using SteamVR for Windows MR and that has the controller model working great. Would love a better solution though...

**Comment by amrittb** [comment]
Oh. Could you elaborate on how you got the controller model using SteamVR?

**Comment by qubitz** [comment]
Absolutely. It works quite well actually.

1) Setup SteamVR on Steam
2) Download [Windows Mixed Reality for SteamVR](http://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/) on Steam. 
3) Start the Windows Mixed Reality Portal
4) Start the Windows Mixed Reality for SteamVR application
5) Set VRTK to use the `SteamVR` setup
6) Hitting play will load up the SteamVR which will hook into MWR for SteamVR and have the WMR controller model

**Comment by amrittb** [comment]
So, you are actually building for Steam VR instead of changing to UWP. I knew that worked, but hadn't noticed the correct controller models loading. Thanks for that info.

**Comment by tomwim** [comment]
@qubytes @amrittb 
About the Error: Did you download the project as ZIP or cloned the repo? There is a github problem when downloading the ZIP that DLLs are marked unsafe and therefore are not recognized by Unity

You also only need this repo if you want to build for UWP. Steam VR will load the controllers on it's own. Steam VR has it's downsides though, but to be fair, so has UWP ;)

**Comment by amrittb** [comment]
Yeah. It seems downloading the ZIP didn't include the DLLs.

**Comment by tomwim** [comment]
You can find a unity package and a zip in releases now
