### ISSUE TITLE
WMR is now part of Master - readme in project needs updating

### ISSUE THREAD

**Issue by SimonDarksideJ** [Innoactive/VRTK-Windows-MR-Extension#5]
The Windows Mixed Reality SDK is now included in the Master for VRTK, so the frontpage Readme should reflect this.

**Comment by tomwim** [comment]
Will update next week and also finally add the unity package bundle. Sorry for the delay...

**Comment by SimonDarksideJ** [comment]
Yeah, will need the Visualizer instructions adding.

Any word @tomwim on creating a downloadable asset for the Visualizer?

**Comment by tomwim** [comment]
You mean as requested in https://github.com/Innoactive/VRTK-Windows-MR-Extension/issues/4 ? Will also follow next week! Promised!

**Comment by SimonDarksideJ** [comment]
Yeah, just linking requests :D

**Comment by tomwim** [comment]
Updated README and the master branch
